### ISSUE TITLE
webshop toevoegen

### ISSUE THREAD

**Issue by Rebel006** [Jan-Bart/belgische-webshops#2]

**Comment by Jan-Bart** [comment]
Dat is bij deze in orde.

208fe3b

**Comment by Rebel006** [comment]
thanks!

**Comment by Marha-bio** [comment]
Beste Jan-Bart,
Zou het mogelijk zijn om https://www.biobey.be/  toe te voegen? Het is een Belgische webshop voor natuurlijke en ecologische verzorging. Alvast bedankt! 
Groetjes Amelia

**Comment by Jan-Bart** [comment]
Dat zou in orde moeten zijn @Marha-bio 

379bba1

**Comment by Marha-bio** [comment]
Beste Jan-Bart,
Super goed! Dank u wel om het toe te voegen. 
Groetjes Amelia
