### ISSUE TITLE
Onze ondernemers online

### ISSUE THREAD

**Issue by santo74** [Jan-Bart/belgische-webshops#3]
Hoi Bart,

https://onzeondernemers.online is ook een initiatief waar Vlaamse ondernemers opgelijst en in de kijker gezet worden.
Misschien kan dit ook mee opgenomen worden in je lijst van initiatieven?

**Comment by Jan-Bart** [comment]
Is bij deze mee opgenomen in de lijst.

572df65150e30dc5f3ebdb1847a27cc80f59e556
